site_name: "Kaspresso"
repo_url: https://github.com/KasperskyLab/Kaspresso
repo_name: Kaspresso
edit_uri: tree/main/docs/content
docs_dir: 'docs'
remote_branch: gh-pages
language: en

theme:
  favicon: kaspresso.png
  logo: kaspresso.png
  icon:
    logo: fontawesome/brands/android

  palette:
    - scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


  name: 'material'
#  custom_dir: ../mkdocs-material/material

  # 404 page
  static_templates:
    - ../mkdocs-material/material/404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
 # favicon: assets/favicon.png
  
  features:
    - navigation.tabs
    - content.code.annotate
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home:
    - About Kaspresso: Home/Kaspresso.md
    - Kaspresso in articles: Home/Kaspresso-in-articles.md
    - Kasspresso in videos: Home/Kaspresso-in-videos.md
    - Our users: Home/Kaspresso users.md
  - Tutorial:
    - Ваш первый тест на Kaspresso: Tutorial/simple_test.md
    - Тестирование за рамками приложения: Tutorial/off-screen_work.md
    - Flaky safely. Сontinuously, compose.: Tutorial/Flaky safely.md
    - Использование сценариев в Kaspresso: Tutorial/Kaspresso_scenario.md
    - Выполнение adb-команд: Tutorial/adb_commands.md
    - Взаимодействуем с Android вне приложения: Tutorial/Device.md 
    - Конфигурирование Kaspresso: Tutorial/Kaspresso_configurator.md
    - Скриншот-тесты: Tutorial/Kaspresso_screenshots.md
    - Использование Allure: Tutorial/Kaspresso_with_allure.md
  - Wiki:
    - Page object in Kaspresso: Wiki/Page object in Kaspresso.md
    - Wrapper over Espresso: Wiki/01_Wrapper_over_Espresso.md
    - Wrapper over UiAutomator: Wiki/02_Wrapper_over_UiAutomator.md
    - Kaspresso configurator: Wiki/03_Kaspresso_configurator.md
    - How to write autotests: Wiki/04_How_to_write_autotests.md
    - Device: Wiki/05_Device.md
    - AdbServer: Wiki/06_AdbServer.md
    - DocLoc: Wiki/07_DocLoc.md
    - Kaspresso Robolectric: Wiki/08_Kaspresso-Robolectric.md
    - Kaspresso Allure: Wiki/09_Kaspresso-Allure.md
    - Jetpack Compose: Wiki/10_Jetpack-Compose.md
  - Documentation:
    - Kaspresso docs: Documentation/kaspresso/index.md
    - KAutomator docs: Documentation/kautomator/index.md
    - ADB Server: Documentation/adb-server/index.md
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# extra:
#  alternate:
#    - name: English
#      link: /en/
#      lang: en
#    - name: Russian
#      link: /ru/
#      lang: ru
